const { PREDICTION_CONTRACT_ABI_BNB } = require('./abi/pancake-prediction-bnb-abi-v3')
const { PREDICTION_CONTRACT_ABI_CAKE } = require('./abi/pancake-prediction-cake-abi-v3')
const { CAKE_CONTRACT_ABI } = require('./abi/cake-contract-abi')

module.exports = {
  PREDICTION_CONTRACT_ABI_BNB,
  PREDICTION_CONTRACT_ABI_CAKE,
  CAKE_CONTRACT_ABI,

  BET_BULL_METHOD_ID_BNB: '0x57fb096f',
  BET_BEAR_METHOD_ID_BNB: '0xaa6b873a',
  CLAIM_METHOD_ID_BNB: '0x6ba4c138',

  BET_BULL_METHOD_ID_CAKE: '0x3923e1b4',
  BET_BEAR_METHOD_ID_CAKE: '0x0e89e5a4',
  CLAIM_METHOD_ID_CAKE: '0x6ba4c138',

  MAX_BET_AMOUNT_BNB: 0.1,
  MIN_BET_AMOUNT_BNB: 0.001,
  BET_AMOUNT_BNB: 0.025,

  MAX_BET_AMOUNT_CAKE: 10,
  MIN_BET_AMOUNT_CAKE: 0.1,
  BET_AMOUNT_CAKE: 0.25,

  SAFE_GAS_PRICE: 5,
  // FAST_GAS_PRICE: 20,
  FAST_GAS_PRICE: 8,

  TOTAL_BETS_INITIAL: 80,
  WIN_RATE_INITIAL: 56,

  TOTAL_BETS: 80,
  WIN_RATE: 56,

  HEXLIFY_SAFE: 200000,
  HEXLIFY_FAST: 350000,
  // HEXLIFY_FAST: 650000,
  // HEXLIFY_FAST: 1000000,
}
