const { PREDICTION_CONTRACT_ABI } = require('./abi/pancake-prediction-abi-v3')

module.exports = {
  PREDICTION_CONTRACT_ABI,

  BET_BULL_METHOD_ID: '0x57fb096f',
  BET_BEAR_METHOD_ID: '0xaa6b873a',
  CLAIM_BEAR_METHOD_ID: '0x6ba4c138',

  MAX_BET_AMOUNT: 0.1,
  MIN_BET_AMOUNT: 0.001,
  BET_AMOUNT: 0.025,

  SAFE_GAS_PRICE: 5,
  FAST_GAS_PRICE: 10,
  // FAST_GAS_PRICE: 6,
  // FAST_GAS_PRICE: 7,

  TOTAL_BETS_INITIAL: 80,
  WIN_RATE_INITIAL: 56,

  TOTAL_BETS: 80,
  WIN_RATE: 56,

  HEXLIFY_SAFE: 300000,
  HEXLIFY_FAST: 650000,
}
