-- CreateTable
CREATE TABLE "Pond" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modifiedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name" TEXT,
    "userId" TEXT NOT NULL,

    CONSTRAINT "Pond_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Pond" ADD CONSTRAINT "Pond_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
