const { PREDICTION_CONTRACT_ABI_BNB } = require('./abi/cake-monsta-abi-v12')

module.exports = {
  PREDICTION_CONTRACT_ABI_BNB,

  // BET_BULL_METHOD_ID_BNB: '0x57fb096f',
  // BET_BEAR_METHOD_ID_BNB: '0xaa6b873a',
  // CLAIM_METHOD_ID_BNB: '0x6ba4c138',

  // MAX_BET_AMOUNT_BNB: 0.1,
  // MIN_BET_AMOUNT_BNB: 0.001,

  // SAFE_GAS_PRICE: 5,
  // FAST_GAS_PRICE: 6,

  // TOTAL_BETS_INITIAL: 80,
  // WIN_RATE_INITIAL: 56,

  // TOTAL_BETS: 80,
  // WIN_RATE: 56,
}
